### ISSUE TITLE
disable guest account

### ISSUE THREAD

**Issue by achuthpv** [achuthpv/ldap_printer#4]
Not able to blacklist guest accounts from accessing the printer via browser. So it will be better to block guest access from the machine.

**Comment by DheerendraRathor** [comment]
I've another idea (other than disabling guest account), which I tested on my machine - Allow only root to print files. This will disallow all other users to print anything. Then use `conn.setPrinterUsersAllowed(printer_name, [username])` in code. This will now allow only that roll number to print.

**Comment by achuthpv** [comment]
Yes, that will do. It is also the best method, since in the method which I suggested, you can still print from the terminal using any name,( other than usernames), which can result in spoofing.
