### ISSUE TITLE
 Geckodriver dependency

### ISSUE THREAD

**Issue by Agrim9** [achuthpv/ldap_printer#6]
It should be mentioned in the readme that the code needs [geckodriver](https://github.com/mozilla/geckodriver) to run. One needs to build the project using rust toolchain and cargo (as mentioned in readme of geckodriver repository), and then copy the driver to/usr/local so as to get the code running. 
Also, a minor correction in readme. The printer.cfg file is in config/ and not data/ .

**Comment by achuthpv** [comment]
I didn't face this issue with geckodriver when I tried to install the script on fresh Ubuntu 14.04. 
So, can you please specify the OS which you are using.

Also, thanks for mentioning the typo. I have corrected it.

**Comment by Agrim9** [comment]
I installed it on a fresh ubuntu 14.04 too, but a 32 bit version. 
Also, there's one more issue. If the script force closes (like ^C in middle of execution), the socket used isn't closed. So, if you run the script again, it throws "Socket already in use exception". I've solved it temporarily by running a script which checks for existing process and killing them before I run the ldap_print command again (which closes the socket, allowing command to be executed perfectly again).

**Comment by achuthpv** [comment]
Writing a handler for SIGINT within the scripts can help fix this issue regarding the open sockets.

Will see if I can do something regarding the geckodriver.

**Comment by achuthpv** [comment]
I have added about the geckodriver into readme.
Also, I have added code for closing the port for Ctl+C. Since I am outside the campus, I am getting certificate issue. Can you please pull the latest code and check if it is working or not ?

It should work. Please reply if there are any further issues. 
Also, thanks for pointing out the issues.

**Comment by Agrim9** [comment]
Yes, the patch works like a charm. Thanks for correcting the issues.
![image](https://cloud.githubusercontent.com/assets/12862791/23338599/4a1e70da-fc35-11e6-8f1e-f39d1c463939.png)
